<?php

namespace Overseer\DTO;

/**
 * Data transfer object for the Character table in the DB
 * 
 * @api
 */
final class CharacterDatabaseDTO {
    public function __construct(
        public int $ID,
        public string $name,
        public string $symbol,
        public int $owner,
        public int $session,
        public int $server,
        public int $client,
        public bool $inmedium,
        public string $land1,
        public string $land2,
        public string $gristType,
        public string $consort,
        public string $class,
        public string $aspect,
        public bool $firstaspectuse,
        public int $wakeself,
        public int $dreamself,
        public int $echeladder,
        public int $godtier,
        public string $abilities,
        public string $aspectpatterns,
        public string $fraymotifs,
        public string $colour,
        public string $dreamer,
        public string $dreamingstatus,
        public int $wakefatigue,
        public int $dreamfatigue,
        public int $fatiguetimer,
        public int $exploration,
        public int $dungeon,
        public int $dungeonrow,
        public int $dungeoncol,
        public int $olddungeonrow,
        public int $olddungeoncol,
        public string $dungeoncoords,
        public string $olddungeoncoords,
        public int $protoPreentry,
        public string $protoObj1,
        public string $protoObj2,
        public string $protoEffects,
        public int $sprite,
        public int $houseBuild,
        public int $gatescleared,
        public int $denizendown,
        public int $down,
        public int $dreamdown,
        public int $boondollars,
        public int $hascomputer,
        public int $equippedcomputer,
        public int $newmessage,
        public int $captchalogues,
        public int $encounters,
        public int $encountersspent,
        public int $lasttick,
        public string $grists,
        public string $inventory,
        public string $metadata,
        public string $strifedeck,
        public string $modus,
        public string $modusvars,
        public int $invslots,
        public string $abstratus,
        public int $abslots,
        public string $equips,
        public string $storeditems,
        public int $storedspace,
        public string $oldenemydata,
        public int $currentquest,
        public int $questland,
        public int $availablequests,
        public int $lastquesttick,
        public int $economy,
        public string $landallies,
        public int $landexplored,
        public string $canaccess,
        public int $luck,
        public string $shopstock,
        public int $lastshoptick,
        public int $consortcount,
        public string $consortequipmentpool,
        public string $enemiesbeaten,
        public string $consortgrist,
        public string $achievements,
        public string $stats,
        public string $notifications,
        public string $notifHistory,
    ) {}
}
