<?php

namespace Overseer\DTO;

final class StriferDatabaseDTO {
    public function __construct(
        public int $id,
        public string $name,
        public int $owner,
        public int $strifeID,
        public int $side,
        public bool $leader,
        public int $teamwork,
        public bool $control,
        public string $grist,
        public string $land,
        public string $description,
        public int $echeladder,
        public int $aspect,
        public int $fatigue,
        public int $power,
        public int $maxpower,
        public int $health,
        public int $maxhealth,
        public int $energy,
        public int $maxenergy,
        public int $luck,
        public int $briefLuck,
        public bool $subaction,
        public string $currentmotif,
        public string $currentmotifname,
        public string $motifsused,
        public bool $teammotif,
        public string $lastactive,
        public string $lastpassive,
        public bool $autopilot,
        public int $autoassist,
        public bool $noassist,
        public bool $cantabscond,
        public string $ondeath,
        public string $status,
        public string $equipstatus,
        public string $bonuses,
        public string $equipbonuses,
        public string $resistances,
        public string $abilities,
        public string $effects,
        public bool $persist,
    ) {}
}
