FROM php:8.2-apache-bookworm

WORKDIR /var/www/html/

# Setup sessions directory
RUN mkdir /var/www/sessions/
RUN chown -R www-data /var/www/sessions/

# Setup composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Copy Apache config
COPY ./config/apache/apache2.conf /etc/apache2/apache2.conf

# Copy project files
COPY ./php/ /var/www/html/
RUN touch /var/www/html/devtools/debuglog.txt
RUN chown -R www-data /var/www/html/

# Run setup
RUN apt-get update
RUN apt-get install -y unzip
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
RUN composer install

# Copy php.ini
COPY ./config/php/prod-php.ini /usr/local/etc/php/php.ini

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
