# Build stage
FROM rust:1.95 AS builder

WORKDIR /app

COPY rust/.sqlx /app/.sqlx
COPY rust/src /app/src
COPY rust/templates /app/templates
COPY rust/Cargo.lock /app/Cargo.lock
COPY rust/Cargo.toml /app/Cargo.toml

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/app/target \
    cargo build --release --features dev && \
    cp target/release/overseer_reboot /usr/local/bin/overseer_reboot


# Runtime stage
FROM debian:bookworm

WORKDIR /app

COPY --from=builder /usr/local/bin/overseer_reboot /usr/local/bin/

COPY rust/static /app/static

CMD ["sh", "-c", "/usr/local/bin/overseer_reboot"]
