# FROM caddy:2.10.0-builder-alpine AS builder

# RUN xcaddy build \
#     --with github.com/caddy-dns/cloudflare \
#     --with github.com/WeidiDeng/caddy-cloudflare-ip

FROM caddy:2.10-alpine
# COPY --from=builder /usr/bin/caddy /usr/bin/caddy

# TODO: Enable Cloudflare DNS support
