name: Deploy

on:
  push:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: 'Create env file, run Docker'
      run: |
          touch .env
          echo DB_HOSTNAME="database" >> .env
          echo DB_USERNAME="root" >> .env
          echo DB_PASSWORD="" >> .env
          echo DB_DATABASE="overseer_v2" >> .env
          echo OVERSEER_ROOT="/php/" >> .env
          echo OVERSEER_PHP_SESSIONS_ROOT="/.session/" >> .env
          echo SITE_HOSTNAME=http://localhost:8000 >> .env
          docker compose stop $(docker compose ps --services)
          docker compose --profile prod up -d --build
